# Generated by Django 4.0.2 on 2022-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('is_chef', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('house_name', models.CharField(default='', max_length=255)),
                ('road_no', models.CharField(default='', max_length=255)),
                ('block_no', models.CharField(default='', max_length=255)),
                ('area', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('district', models.CharField(default='', max_length=255)),
                ('mobilePhone', models.CharField(default='', max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='', upload_to='')),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
