# Generated by Django 4.0.2 on 2022-02-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profile_picture',
        ),
    ]
