# Generated by Django 4.0.2 on 2022-03-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopID', models.IntegerField(default=0)),
                ('itemName', models.CharField(default='No name', max_length=100)),
                ('cost', models.FloatField(default=0, max_length=10)),
                ('accumulatedRating', models.FloatField(default=0, max_length=10)),
                ('itemImg', models.CharField(default='No name', max_length=100)),
                ('itemDetail', models.CharField(default='', max_length=300)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['itemName'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('shopName', models.CharField(default='No name', max_length=100)),
                ('review', models.FloatField(default=0, max_length=10, null=True)),
                ('isBanned', models.BooleanField()),
                ('detailedAddr', models.CharField(default='', max_length=300)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['shopName'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='No name', max_length=100)),
                ('lastName', models.CharField(default='No name', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('phNo', models.IntegerField(default=0, max_length=11, null=True)),
                ('emailAddr', models.CharField(default='', max_length=100)),
                ('timeStampUpdated', models.DateTimeField(auto_now=True)),
                ('timeStampCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['emailAddr'],
            },
        ),
    ]
