# Generated by Django 4.0.2 on 2022-03-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofileinfo_is_profile_pic_updated_and_more'),
        ('GhorKuno', '0002_contactus_createdtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['user_id']},
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(default='', max_length=100)),
                ('review', models.FloatField(blank=True, default=0, max_length=5)),
                ('isBanned', models.BooleanField(default=False)),
                ('detailedAddr', models.CharField(default='', max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofileinfo')),
            ],
            options={
                'ordering': ['shopName'],
            },
        ),
    ]
