# Generated by Django 4.0.2 on 2022-03-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofileinfo_is_profile_pic_updated_and_more'),
        ('GhorKuno', '0003_alter_contactus_options_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner', to='accounts.userprofileinfo'),
        ),
    ]
